---
title: "Fundamentals of Microscopy workshop"
---

The [Bio-Imaging Resource Center](https://www.rockefeller.edu/bioimaging/) (BIRC) and the [Miller Brain Observatory](https://mbo.rockefeller.edu/) (MBO) are pleased to invite you to a **Fundamentals of Microscopy** workshop series designed to help you take your imaging to the next level. This workshop will be suitable for people using the microscopes in our centers or in their own laboratories.

This series will consist of five sessions, most of which will comprise:  

- a 45-minute lecture,  
- 15 minutes of Q&A, and  
- 2 hours of hands-on practical training, using the microscopes in our centers.  

The workshop sessions will be scheduled from 9.30 am till 12.30 pm once a month on a Thursday, (with coffee and cookies provided at the start!):

|#|Topic|Date|Speaker|
|----|----|----|----|
|1|Fundamentals of Fluorescence and the Fluorescence Microscope|January 29|Dr. Alison North, BIRC|
|2|What Is an Image? Image capture, composition and basic analysis|February 26|Dr. Ved Sharma, BIRC|
|3|Light Properties and Optical Principles|March 26|Dr. Behzad Khajavi, BIRC|
|4|Confocal Microscopy|April 30|Dr. Ivan Rey Suarez, BIRC|
|5|Light-Sheet Microscopy|May 28|Dr. Raghav Chhetri, MBO|

: Session info {tbl-colwidths="[3,51,16,30]"}

Attendees will be expected to attend all 5 sessions if possible, to ensure continuity of learning.  The cost of the registration will be $250 in total for the 5 sessions (partial registrations will not be permitted), and the workshop will be capped at 30 participants to ensure access to all microscopes during the practical rotations.

The deadline for registration is Thursday January 22, 2026.

After registration, you will receive a confirmation email. We will follow up closer to the date with additional information.

If the attendance is sufficiently high, we will follow up with a second series on more advanced techniques, such as super-resolution, multiphoton, single molecule techniques, F-techniques, and advanced image analysis methods.
We look forward to your participation and hope you will join us for this engaging and practical series.

## Learning objectives

After successful completion of this workshop, participants should be able to:

- Understand the different properties of light (reflection, refraction, diffraction etc.) that are utilized to generate an optical microscopy image;
- Be familiar with the components and design of both basic and more advanced microscopes; 
- Know how to pick the most suitable objective lens on the microscope for a given sample and application, including what determines - and limits - the attainable resolution;
- Understand the physical principles behind fluorescence and how to choose a specific fluorochrome or combination of dyes for a biological experiment, including properties of an ideal fluorochrome and the advantages and disadvantages of using shorter or longer wavelength dyes;
- Be capable of picking or ordering a suitable filter set to use with a given combination of fluorophores; 
- Understand how photons from the specimen are turned into digital images and factors affecting the image quality (camera noise, pixel size etc.);
- Learn how to avoid common pitfalls such as saturation or undersampling that can prevent your data from being quantitative;
- Know when confocal microscopy is required and when widefield microscopy is more appropriate, based on the biological question and sample characteristics;
- Understand and predict the impact of key confocal parameters—including pinhole size, scan area, zoom/magnification, laser power, and related settings—on image resolution, contrast, signal-to-noise ratio, and photobleaching;
- Be familiar with alternative optical sectioning methods such as light-sheet microscopy, and appreciate the benefits of light-sheet vs. confocal for a given specimen and biological question;
- Be aware of the myriad of different light-sheet microscope designs and configurations, applicable to distinct research questions;
- Understand image bit depth, file formats, metadata and multidimensional images (channels, time series); 
- Perform common image processing tasks (adjusting brightness/contrast, scale bar, ROIs, intensity measurements) in ImageJ/Fiji more effectively and understand when to use image processing filters (Gaussian, Edge detection etc.) to help with cell/nucleus segmentation.

